---
title: "p8105_hw2_ha2546"
author: "Hana Akbarnejad"
date: "9/27/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
```

```{r Mr.Trash Wheel}

library(readxl)

trash_data = 
  read_excel("data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = "Mr. Trash Wheel") %>% 
  janitor::clean_names() %>% 
  select(-x15) %>% 
  drop_na(dumpster) %>% 
  mutate(
    sports_balls = round(sports_balls),
    as.integer(sports_balls)
  )

```

```{r precipitation}

prcpt2017_data = 
  read_excel("data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = "2017 Precipitation", skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(
    year = "2017"
  )

prcpt2018_data = 
  read_excel("data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = "2018 Precipitation", skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(
    year = "2018"
  )

prcpt_data =
  bind_rows(prcpt2017_data, prcpt2018_data) %>% 
  mutate(
    month = format(month(num = c(1:12)), month.name)
  )
```

